ENH: script can be run in any place and support re-running the code (#16)
* support serial job and start submit job under inifile directory

* now cd to the directory of parameter file at first and FILE.ini is optional

* support directly re-running

* optimize log message for skipping steps

* not modify job script when it is in the output directory

diff --git a/bin/psub b/bin/psub
--- a/bin/psub
+++ b/bin/psub
@@ -2,6 +2,8 @@
 
 # Total steps of workflow
 steps=6
+istep=0
+origin=$(pwd)
 # generate by $ pyfiglet -j center -f smslant "PLUTO Job Submission" 
 printf "\e[2m"
 printf "%s\n" "           ___  __   __  ____________       __     __   "
@@ -14,7 +16,7 @@ printf "%s\n" "          _\ \/ // / _ \/  ' \/ (_-<(_-</ / _ \/ _ \    "
 printf "%s\n" "         /___/\_,_/_.__/_/_/_/_/___/___/_/\___/_//_/    "
 printf "\e[0m\n"
 
-usage="Usage: psub [-h] [-n] [-x] [-j jobscript] [-s src_dir] FILE.in"
+usage="Usage: psub [-h] [-n] [-x] [-j jobscript] [-s src_dir] [FILE.ini]"
 while getopts 'hnxj:s:' OPTNAME; do
     case "$OPTNAME" in
     h)
@@ -29,7 +31,7 @@ while getopts 'hnxj:s:' OPTNAME; do
         printf "%s\n" "$usage"
         printf "%s\n" "-h,    This help text"
         printf "%s\n" "-n,    Not submit job script"
-        printf "%s\n" "-x,    Not change executable file pluto"
+        printf "%s\n" "-x,    Not change definitions.h and the executable pluto"
         printf "%s\n" "-j,    Specify filename of job script. Default: job.s"
         printf "%s\n" "-s,    Specify the directory of source code. Default: \${filepath%/runs*}/code/"
         exit 0
@@ -40,7 +42,7 @@ while getopts 'hnxj:s:' OPTNAME; do
         ;;
     x)
         no_pluto=true
-        steps=$(($steps - 1))
+        steps=$(($steps - 2))
         ;;
     j)
         jobscript=$(readlink -f $OPTARG)
@@ -66,16 +68,25 @@ kw="\e[96m%s\e[0m"
 arw="\e[92;1m->\e[0m"
 
 # Get Pluto parameter file
-filepath=$(readlink -f $1)
-if [ ! -f $filepath ]; then
-    printf "$err $kw does not exist !\n" $filepath
+if [ ! -f $1 ]; then
+    printf "$err $kw does not exist !\n" $1
     exit 1
 fi
+inifile=$1
+if [ -z $1 ]; then
+    inifile=pluto.ini
+else
+    inifile=$1
+fi
+inifile=$(readlink -f $inifile)
+printf "$log Specified parameter file: $kw\n" $inifile
+directory=$(dirname $inifile)
+filename=$(basename $inifile)
 
 # 1. Parsing and create output directory
-output_dir=$(awk '{if ($1 == "output_dir") print $2}' $filepath)
-output_dir=$(readlink -f $(dirname $filepath)/$output_dir)
+output_dir=$(awk '{if ($1 == "output_dir") print $2}' $inifile)
 if [ $output_dir ]; then
+    output_dir=$(readlink -f $directory/$output_dir)
     printf "$log Parsed output directory: $kw\n" $output_dir
     if [ -d $output_dir ]; then
         printf "$log Output directory already exits, so just use it\n"
@@ -85,72 +96,103 @@ if [ $output_dir ]; then
     else
         mkdir $output_dir
     fi
+    istep=$(($istep + 1))
+    printf "$stp Create output directory: $kw\n" $istep $output_dir
+    if [ $directory ]; then
+        cd $directory
+        printf "$log cd to: $kw\n" $(pwd)
+    else
+        printf "$err Cannot parse directory of parameter file!\n"
+        exit 1
+    fi
 else
+    output_dir=$origin
     printf "$log No specified output directory, outputs will be saved in the current directory\n"
+    istep=$(($istep + 1))
+    printf "$stp Determine output directory: $kw\n" $istep $output_dir
 fi
-    printf "$stp Create output directory: $kw\n" 1 $output_dir
+
+# If running under output directory and not specified parameter file,
+# consider it as a re-running
+if [[ -z $1 && $output_dir == $origin ]]; then
+    no_pluto=true
+fi
 
 # 2. Create or override the soft link pluto.ini
-inifile=$output_dir/pluto.ini
+inipluto=$output_dir/pluto.ini
 # Use relative path for link
-rel_filepath=$(realpath --relative-to=$output_dir $filepath)
-if [ -f $inifile ]; then
+rel_filepath=$(realpath --relative-to=$output_dir $inifile)
+if [ -f $inipluto ]; then
     # Override
-    if [ -L $inifile ]; then
-        rm $inifile
-        ln -s $rel_filepath $inifile &&
-        printf "$stp Link pluto.ini: $kw $arw $kw\n" 2 $inifile $rel_filepath
+    if [ -L $inipluto ]; then
+        rm $inipluto
+        ln -s $rel_filepath $inipluto &&
+        istep=$(($istep + 1)) &&
+        printf "$stp Link pluto.ini: $kw $arw $kw\n" $istep $inipluto $rel_filepath
     else
-        printf "$log $kw already exits but is not a symbolic link, so just use it\n" $inifile &&
-        printf "$stp Use $kw itself\n" 2 $inifile
+        printf "$log $kw already exits but is not a symbolic link, so just use it\n" $inipluto &&
+        istep=$(($istep + 1)) &&
+        printf "$stp Use $kw itself\n" $istep $inipluto
     fi
 else
     # Create
-    ln -s $rel_filepath $inifile &&
-    printf "$stp Link pluto.ini: $kw $arw $kw\n" 2 $inifile $rel_filepath
+    ln -s $rel_filepath $inipluto &&
+    istep=$(($istep + 1)) &&
+    printf "$stp Link pluto.ini: $kw $arw $kw\n" $istep $inipluto $rel_filepath
 fi
 
-# 3. Copy definitions.h to the output directory
-if [ -z $src ]; then
-    src=${filepath%/runs*}/code
-fi
-if [ ! -d $src ]; then
-    printf "$err Directory of source code does not exist: $kw\n" $src
-    exit 1
-fi
-cp $src/definitions.h $output_dir &&
-printf "$stp Copy definitions.h: $kw $arw $kw\n" 3 $src/definitions.h $output_dir/definitions.h
-# 4. Copy pluto to the output directory
+# 3. Copy definitions.h and pluto from source code to the output directory
 if [ -z $no_pluto ]; then
+    if [ -z $src ]; then
+        src=${directory%/runs*}/code
+    fi
+    printf "$log Determine source code directory: $kw\n" $src
+    if [ ! -d $src ]; then
+        printf "$err Directory of source code does not exist: $kw\n" $src
+        exit 1
+    fi
+    cp $src/definitions.h $output_dir &&
+    istep=$(($istep + 1)) &&
+    printf "$stp Copy definitions.h: $kw $arw $kw\n" $istep $src/definitions.h $output_dir/definitions.h
+
     cp $src/pluto $output_dir &&
-    printf "$stp Copy pluto: $kw $arw $kw\n" 4 $src/pluto $output_dir/pluto
+    istep=$(($istep + 1)) &&
+    printf "$stp Copy pluto: $kw $arw $kw\n" $istep $src/pluto $output_dir/pluto
 else
-    printf "$stp Do not change pluto\n" 4
+    istep=$(($istep + 1)) &&
+    printf "$stp Skip updating definitions.h\n" $istep
+    istep=$(($istep + 1)) &&
+    printf "$stp Skip updating pluto\n" $istep
 fi
 
 # Set default filename of job script to job.s
-jobscript_name=job.s
 if [ -z $jobscript ]; then
-    jobscript=$(readlink -f job.s)
-    jobscript_name=$(basename $jobscript)
+    jobscript=$origin/job.s
 fi
+jobscript_name=$(basename $jobscript)
 
 # Task name is the init filename without extension
-taskname=$(basename $filepath .ini);
+taskname=$(basename $inifile .ini);
 printf "$log Parsed taskname: $kw\n" $taskname
 # 5. Replace some fields in job script with task name, the fields include
 # job name
 # output filename
 # error filename
 if [ -e $jobscript ]; then
-    sed -r -e \
-    "\
-    s|(^#BSUB[ ]+-J[ ]+)[^ ]+([ ]*.*)$|\1$taskname\2|;\
-    s|(^#BSUB[ ]+-o[ ]+)[^ ]+([ ]*.*)$|\1$output_dir/%J.out\2|;\
-    s|(^#BSUB[ ]+-e[ ]+)[^ ]+([ ]*.*)$|\1$output_dir/%J.err\2|;\
-    s|(^.*[ ]+)[^ ]+pluto(.*-i[ ]+)[^ ]+(.*)|\1$output_dir/pluto\2$inifile\3|;\
-    " $jobscript > $output_dir/$jobscript_name &&
-    printf "$stp Create/Override: $kw\n" 5 $output_dir/$jobscript_name
+    if [ $jobscript == $output_dir/$jobscript_name ]; then
+        printf "$log Template job script is already in output directory, so just use it\n"
+    else
+        sed -r -e \
+        "\
+        s|(^#BSUB[ ]+-J[ ]+)[^ ]+([ ]*.*)$|\1$taskname\2|;\
+        s|(^#BSUB[ ]+-o[ ]+)[^ ]+([ ]*.*)$|\1$output_dir/%J.out\2|;\
+        s|(^#BSUB[ ]+-e[ ]+)[^ ]+([ ]*.*)$|\1$output_dir/%J.err\2|;\
+        s|(^.*[ ]+)[^ ]+pluto(.*-i[ ]+)[^ ]+(.*)|\1$output_dir/pluto\2$inifile\3|;\
+        s|^./pluto(.*-i[ ]+)[^ ]+(.*)|$output_dir/pluto\1$inifile\2|;\
+        " $jobscript > $output_dir/$jobscript_name &&
+        istep=$(($istep + 1)) &&
+        printf "$stp Create/Override: $kw\n" $istep $output_dir/$jobscript_name
+    fi
 else
     printf "$err Tempelate job script $kw does not exist !\n" $jobscript
     exit 1
@@ -159,7 +201,8 @@ fi
 # 6. submit job script
 if [ -z $no_submit ]; then
     submit=$(bsub < $output_dir/$jobscript_name) &&
-    printf "$stp Submit job script: %s\n" 6 "$submit"
+    istep=$(($istep + 1)) &&
+    printf "$stp Submit job script: %s\n" $istep "$submit"
 else
     printf "$log Not submit job script\n"
 fi
